name: run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: |
          GOPRIVATE=github.com/kentik
          go test -v -mod=vendor github.com/kentik/libkflow/...
